### ISSUE TITLE
Bump to Marshmallow 3?

### ISSUE THREAD

**Issue by multimeric** [socialwifi/flask-jsonapi#47]
I've already written some schemas and code that only works with Marshmallow 3. Is there any interest in a new (major) release that uses Marshamallow 3?

**Comment by jgoclawski** [comment]
Yes, we intend to upgrade to Marshmallow 3, but we don't have any time estimate when it will be done. If you'd like to contribute with a PR, that would be great.

**Comment by multimeric** [comment]
Ah great. Yeah I'm happy to do it myself, I just wanted to check that it was on the roadmap.

**Comment by multimeric** [comment]
Hmm, on second thoughts this is much more complex than just plain marshmallow under the hood. In theory you only need to do little things like changing `data, errors = schema().dump()` to `data = schema().dump()`, but this library is a touch too complex for me to be able to fix all the failing tests.

**Comment by multimeric** [comment]
But in any case I'll leave the small amount of work I've done here, in case it ends up being useful: https://github.com/socialwifi/flask-jsonapi/pull/48

**Comment by jgoclawski** [comment]
Merged in #51, released as version 0.11.0 on pypi.
