### ISSUE TITLE
Potential dependency conflicts between flask-jsonapi and marshmallow

### ISSUE THREAD

**Issue by NeolithEra** [socialwifi/flask-jsonapi#50]
Hi, as shown in the following full dependency graph of **_flask-jsonapi_**, **_flask-jsonapi_** requires **_marshmallow <3.0.0_**, **_flask-jsonapi_** requires **_marshmallow-jsonapi *_** (**_marshmallow-jsonapi 0.23.1_** will be installed, i.e., the newest version satisfying the version constraint), and directed dependency **_marshmallow-jsonapi 0.23.1_** transitively introduces **_marshmallow >=2.15.2_**.

Obviously, there are multiple version constraints set for **_marshmallow_** in this project. However, according to pip's _“first found wins”_ installation strategy, **_marshmallow 2.21.0_** (i.e., the newest version satisfying constraint **_<3.0.0_**) is the actually installed version.

Although the first found package version **_marshmallow 2.21.0_** just satisfies the later dependency constraint （**_marshmallow >=2.15.2_**), such installed version is very close to the upper bound of the version constraint of Marshmallow specified by **_marshmallow-jsonapi 0.23.1_**. 

Once **_marshmallow-jsonapi_** upgrades，its newest version will be installed, as **_flask-jsonapi_** does not specify the upper bound of version constraint for **_marshmallow-jsonapi_**. Therefore, it will easily cause a dependency conflict (build failure), if the upgraded **_marshmallow-jsonapi_** version introduces a higher version of **_Marshmallow_**, violating its another version constraint **_<3.0.0_**.

According to the release history of **_marshmallow-jsonapi_**, it habitually upgrates **_Marshmallow_** in its recent releases. For instance, **_marshmallow-jsonapi 0.21.2_** upgrated Marshmallow’s constraint from **_>=2.8.0 to >=2.15.0_**, and **_marshmallow-jsonapi 0.22.0_** upgrated Marshmallow’s constraint from **_>=2.15.0 to >=2.15.2_**. 

As such, it is a warm warning of a potential dependency conflict issue for flask-jsonapi.

### Dependency tree
```
flask-jsonapi - 0.10.3
| +- flask(install version:1.1.2 version range:*)
| | +- click(install version:7.1.1 version range:>=5.1)
| | +- itsdangerous(install version:1.1.0 version range:>=0.24)
| | +- Jinja2(install version:2.11.2 version range:>=2.10.1)
| | | +- MarkupSafe(install version:2.0.0a1 version range:>=0.23)
| | +- Werkzeug(install version:1.0.1 version range:>=0.15)
| +- marshmallow(install version:2.21.0 version range:<3.0.0)
| +- marshmallow-jsonapi(install version:0.23.1 version range:*)
| | +- marshmallow(install version:2.21.0 version range:>=2.15.2)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution
1.	Loosen the version range of **_marshmallow_** to be **_>=2.21.0_**.
2.	Remove your direct dependency **_marshmallow_**, and use the **_marshmallow_** transitively introduced by **_marshmallow-jsonapi_**.
3.	Change your direct dependency **_marshmallow-jsonapi_** to be **_<=0.23.1_**.
@ jgoclawski  Which solution do you prefer, 1 ,2or 3?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by jgoclawski** [comment]
Hi @NeolithEra, thanks for the detailed report.

I'm not sure if I understand correctly, but if "flask-jsonapi requires marshmallow <3.0.0" and "marshmallow-jsonapi requires marshmallow >=2.15.2." then everything is fine and any version of marshmallow in the range of [2.15.2, 3.0.0) should work and I think it is.
The range is the effect of assumptions that marshmallow-jsonapi supports both branches of marshmallow: 2.x and 3.x (added in https://github.com/marshmallow-code/marshmallow-jsonapi/pull/100) while flask-jsonapi does not have support for marshmallow 3.x yet (#47).

To sum: I don't think we need to do anything as long as marshmallow-jsonapi supports marshmallow 2.x. The best way to move forward would be of course to add support for marshmallow 3.x for flask-jsonapi (#47)

**Comment by NeolithEra** [comment]
@jgoclawski Thank you for your feedback! Looking forward to seeing a new release of  flask-jsonapi that support marshmallow 3.x. This is just a warm prompt for potential dependency conflict issues.
