### ISSUE TITLE
What is the difference compare to Flask-REST-JSONAPI?

### ISSUE THREAD

**Issue by firdaus-aziz** [socialwifi/flask-jsonapi#54]
May I know what is the difference between this versus Flask-REST-JSONAPI?

**Comment by jgoclawski** [comment]
Hi @nuthingman. While, we don't keep an up to date comparison between different JSON:API server implementations, I know there are some architecture differences (e.g. DataLayer vs Repository pattern) between the two packages. I believe Flask-REST-JSONAPI might have more features implemented.
You can compare the docs to see the differences. Check the examples and see which architecture fits your needs better.
* https://flask-jsonapi.readthedocs.io/en/latest/
* https://flask-rest-jsonapi.readthedocs.io/en/latest/
